#+TITLE: Christianity Resources
#+AUTHOR: Chris Lockard
#+EMAIL: @unl0ckd@fosstodon.org

* Bibles
- NIV
  The [New International
Version][https://en.wikipedia.org/wiki/New_International_Version] is an
approachable Dynamic Equivalence translation of the Protestant Bible.
- NLT The [New Living
  Translation][https://en.wikipedia.org/wiki/New_Living_Translation] is an even
  more approachable Dynamic Equivalence translation of the Protestant Bible.

* Websites
- Bible Gateway (https://www.biblegateway.com) has a clean layout, support for
  many translations, and useful comparison and chapter:verse lookup tools.
* Books
- [When Skeptics Ask - Norman L.
  Geisler][https://web.archive.org/web/https://www.christianbook.com/skeptics-handbook-christian-evidences-revised-updated/norman-geisler/9780801014987/pd/014987]
  is a book on Christian Apologetics that offers a rational proof of the
  existence of God and of Christianity as His religion on earth.
- [Secrets From Heaven][https://shop.catholic.com/secrets-from-heaven/] is an
  insightful and revelatory look at some of the famous parables in the Bible.
  The author explains the literal and spiritual significance of these passages
  and offers tips for evangelizing the Gospel based on them.
